spring:
  application:
    name: "dbms-healthcare"
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/healthcare?authSource=admin
      auto-index-creation: true

server:
  max-http-request-header-size: 65536

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE