spring:
  application:
    name: "dbms-healthcare"
  data:
    mongodb:
<<<<<<< HEAD
      uri: mongodb://localhost:27017/healthcare
      auto-index-creation: true
=======
      uri: mongodb://user:pass@localhost:27017/healthcare?authSource=admin
      auto-index-creation: true
      admin:
        uri: mongodb://admin_user:admin_pass@localhost:27017/healthcare?authSource=healthcare
      doctor:
        uri: mongodb://doctor_user:doctor_pass@localhost:27017/healthcare?authSource=healthcare
      patient:
        uri: mongodb://patient_user:patient_pass@localhost:27017/healthcare?authSource=healthcare
>>>>>>> temp-main

server:
  max-http-request-header-size: 65536

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE