spring:
  application:
    name: "dbms-healthcare"
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/healthcare?authSource=admin

server:
  max-http-request-header-size: 65536

jwt:
  rsa-public-key: classpath:keys/public_key.pem
